import { motion } from "framer-motion";
import { formatCurrency } from "../../utils/formatters";

// Derives commentary purely from the forecast array.
// No backend fields are fabricated — everything stated here is
// mathematically derived from the predicted_close values.
function buildCommentary(ticker, forecast) {
  const day1 = forecast[0].predicted_close;
  const day10 = forecast[forecast.length - 1].predicted_close;
  const delta = day10 - day1;
  const deltaPct = day1 !== 0 ? (delta / day1) * 100 : 0;
  const threshold = day1 * 0.005; // 0.5%
  let direction = "sideways";
  let directionAdj = "neutral";
  if (delta > threshold) {
    direction = "upward";
    directionAdj = "bullish";
  } 
  else if (delta < -threshold) {
    direction = "downward";
    directionAdj = "bearish";
  }

  const prices = forecast.map((d) => d.predicted_close);
  const min = Math.min(...prices);
  const max = Math.max(...prices);
  const range = max - min;
  const volatilityDesc = range / day1 > 0.03 ? "noticeable" : "modest";

  // Detect if the trajectory is monotone or has reversals
  let reversals = 0;
  for (let i = 1; i < prices.length - 1; i++) {
    const prev = prices[i] - prices[i - 1];
    const next = prices[i + 1] - prices[i];
    if (Math.sign(prev) !== Math.sign(next)) reversals++;
  }
  const trajectoryDesc =
    reversals <= 1 ? "consistent" : reversals <= 3 ? "slightly volatile" : "mixed";

  const bullets = [
    `The model predicts ${ticker} will move ${direction} over the next 10 trading days.`,
    `Day 1 opens at ${formatCurrency(day1)}, reaching ${formatCurrency(day10)} by Day 10 — a ${
      delta >= 0 ? "gain" : "loss"
    } of ${formatCurrency(Math.abs(delta))} (${Math.abs(deltaPct).toFixed(2)}%).`,
    `The 10-day projected price range spans ${formatCurrency(min)} to ${formatCurrency(
      max
    )}, indicating ${volatilityDesc} volatility.`,
    `The predicted trajectory is ${trajectoryDesc}, with ${reversals} directional ${
      reversals === 1 ? "reversal" : "reversals"
    } across the forecast window.`,
  ];

  return { direction, directionAdj, deltaPct, bullets };
}

const TONE_STYLES = {
  bullish: "border-bull/30 bg-bull-soft",
  bearish: "border-bear/30 bg-bear-soft",
  neutral: "border-base-border bg-base-panel",
};

export default function ForecastCommentary({ ticker, forecast }) {
  const { directionAdj, deltaPct, bullets } = buildCommentary(ticker, forecast);
  const toneStyle = TONE_STYLES[directionAdj] || TONE_STYLES.bearish;
  const toneText = directionAdj === "bullish" ? "text-bull-text" : "text-bear-text";

  return (
    <motion.section
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, delay: 0.15 }}
      className={`relative overflow-hidden rounded-lg border p-6 sm:p-7 ${toneStyle}`}
    >
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-base-border pb-4">
        <h2 className="flex items-center gap-2 font-display text-lg font-semibold text-ink-primary">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true" className="text-accent">
            <path d="M12 2a10 10 0 1 0 0 20A10 10 0 0 0 12 2Z" stroke="currentColor" strokeWidth="1.6" />
            <path d="M12 8v4l3 3" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
          </svg>
          KickStock's Forecast Commentary
        </h2>
        <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-2xs font-semibold uppercase tracking-wide ${toneStyle} ${toneText}`}>
          {Math.abs(deltaPct).toFixed(2)}%{" "}
          {directionAdj === "bullish" ? "Projected Gain" : "Projected Loss"}
        </span>
      </div>

      <ul className="mt-4 flex flex-col gap-2.5">
        {bullets.map((bullet, i) => (
          <motion.li
            key={i}
            initial={{ opacity: 0, x: -6 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.25, delay: 0.2 + i * 0.07 }}
            className="flex items-start gap-2.5 text-sm leading-relaxed text-ink-secondary"
          >
            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
            <span>{bullet}</span>
          </motion.li>
        ))}
      </ul>

      <div className={`mt-5 rounded-md border px-4 py-3 text-sm leading-relaxed ${toneStyle} ${toneText}`}>
        <span className="mb-1 block text-2xs font-semibold uppercase tracking-wide opacity-80">
          Disclaimer
        </span>
        These predictions are generated by a machine learning model and reflect statistical
        patterns only. They are not financial advice and should not be used as the sole basis
        for investment decisions.
      </div>
    </motion.section>
  );
}